name: 'github-file-reader-v2'
description: 'Read the contents of a file'
author: 'GuiBranco'
branding:
  icon: 'file-text'
  color: 'blue'
inputs:
  path:
    description: 'The path to the file to be read.'
    required: true
  encoding:
    description: 'The encoding of the file.'
    default: 'utf8'
    required: false
outputs:
  contents:
    description: 'The file contents.'
runs:
  using: 'node16'
  main: 'dist/index.js'
