# Unordered list style
MD004:
  style: dash

# Ordered list item prefix
MD029:
  style: one

# MD013/line-length - Line length
MD013: false

# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements: ['p', 'a', 'img']

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false
