name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
            path: "README.md"

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.contents }}"

  create-release:
    name: Create release
    needs: [test-typescript, test-action]
    runs-on: ubuntu-latest
    steps:
     
    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        allowUpdates: false
        draft: false
        makeLatest: true
        tag: v2.0.${{ github.run_number }}
        name: Release v2.0.${{ github.run_number }}
        generateReleaseNotes: true
        body: Release 2.0.${{ github.run_number }} of GitHub Actions File Reader V2